### ISSUE TITLE
Bring back baserel support...

### ISSUE THREAD

**Issue by jens-maus** [sba1/adtools#14]
GCC 4.0.4 have been the last version supporting baserel compilation for AmigaOS4 target. After that it had been removed from our patches for some unknown reasons.

Since there are projects like https://github.com/jens-maus/amissl strongly relying on baserel compilation it would be really great if our baserel patches could be readded to our patchset. Here the Amissl project could serve as a perfect test case due to its high conplexity and strong use of global variables in the library interface...

**Comment by sba1** [comment]
I fixed a bug in our gcc 8 branch that could improve the situation (the bug was present at least since adtools gcc 4.9). As binutils 2.23.2 does not support the new reloc types yet, I can't say if this produces working code. If still interested, you could test it with an older binutils.

I'll try to build few tests and possibly look into the linker to see if it can be easily fixed in the next following days.

**Comment by sba1** [comment]
With my latest binutils changes, I'm able to compile and link programs. I haven't tested resulting programs yet (I'll design a small test) but in principle, it would be okay if some larger project is tried now. Resulting problems should be isolated though. I think that would help to have proper support soon.

A test should involve gcc 8 and binutils 2.23.2.

**Comment by sba1** [comment]
I've just fixed another bug that led to corrupted binaries when optimization was turned on.

**Comment by sba1** [comment]
I added a few micro tests and they pass. Although this is not representative I think that the most important problems have been fixed now. Therefore I'll close this issue. Please file a new issue if you encounter a new problem.
